#!/usr/bin/env bash

echo "Using Adwaita as a Baseline"
mkdir -p package
rm -rf ./package/*
cp -r /usr/share/themes/Adwaita-dark/* ./package/

echo "Generating Index File"
rm -f ./package/index.theme
cat << EOF > ./package/index.theme
[X-GNOME-Metatheme]
Name=Adwaita Solarized
Type=X-GNOME-Metatheme
Comment=Solarized Dark version of GNOME's Adwaita theme.
Encoding=UTF-8
GtkTheme=Adwaita-dark
IconTheme=Adwaita
CursorTheme=Adwaita
CursorSize=24
EOF

echo "Generating Assets"
./render-assets
cp -rn ./assets/* ./package/gtk-2.0/assets/

echo "Generating Theme Files"
sassc -M -t compact gtk-contained.scss ./package/gtk-3.0/gtk.css
cp gtkrc ./package/gtk-2.0/gtkrc
